# -*- coding: utf-8 -*-
"""P1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D3mAu2XVj21wX6hKm6yTXhaqdL-hhE9a
"""

x1, y1 = map(int, input().split())
x2, y2 = map(int, input().split())

if abs(x2 - x1) <= 1 and abs(y2 - y1) <= 1:
    if (x1, y1) == (x2, y2):
        print("No")
    elif checkerboard[x2][y2] == 1:
        print("No")
    else:
        print("Yes")
else:
    print("No")